# Generated by Django 5.2.17 on 2026-09-28 14:27

import portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=portal.fields.EncryptedTextField(blank=True, max_length=50),
        ),
    ]
