# Generated by Django 5.2.17 on 2026-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_user_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='provider_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_status',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
