# Generated by Django 4.2.30 on 2026-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_user_removed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='service_type',
            field=models.CharField(choices=[('travel', 'Travel request'), ('flight', 'Flights'), ('hotel', 'Hotel'), ('package', 'Flights & hotel'), ('transfer', 'Transfers')], default='travel', max_length=12),
        ),
    ]
